<?php $year = date("Y");?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html"/>
    <?php echo $this->headTitle()->setAutoEscape(false);?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <style type="text/css">
        body {
            margin: 0;
            padding: 0;
            font-family: 'Arial', sans-serif;
            background-color: white;
        }
    </style>
</head>
<body>

<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td>
            <table width="600px" align="center" border="0" cellpadding="0"  cellspacing="0"  style="border-collapse: collapse;">
                <tr>
                    <?php //Add a header row here ?>
                </tr>
                <tr>
                    <td style="padding: 40px 30px 40px 30px;">
                        <?php echo $this->message;?>
                    </td>
                </tr>
                <tr>
                    <?php //footer row ?>
                    <td style="padding: 20px 30px 10px 30px; font-size: 70%;">
                        <p style="margin: 0 0 2px 0;">You are receiving this email because you are a user of example.com</p>
                        <p style="margin: 0 0 0 0;"><?= sprintf('&copy; example.com %s. All rights reserved.', $year);?></p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>

