<?php $year = date("Y");?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html"/>
    <?php echo $this->headTitle()->setAutoEscape(false);?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <style type="text/css">
        body {
            margin: 0;
            padding: 0;
            font-family: 'Arial', sans-serif;
            background-color: white;
        }
        .mail-header {
            margin-bottom: 10px;
        }
        .mail-body {
            margin-bottom: 10px;
        }
        .mail-footer {
            font-size: 70%;
            padding: 20px 10px 10px 10px;
        }
    </style>
</head>
<body>

<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td>
            <table align="left" border="0" cellpadding="0"  cellspacing="0"  style="border-collapse: collapse;">
                <tr>
                    <td class="mail-header">
                        <p>This is the header section</p>
                    </td>
                </tr>
                <tr>
                    <td class="mail-body">
                        <?php // content from child view models ?>
                        <p><?php echo $this->message;?></p>
                    </td>
                </tr>
                <tr>
                    <?php //footer row ?>
                    <td class="mail-footer">
                        <p>You are receiving this email because you are a user of example.com</p>
                        <p><?= sprintf('&copy; example.com %s. All rights reserved.', $year);?></p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>

